
USE [LensOptikDB]

DECLARE @GUNFIYAT money
DECLARE @GUNID int
DECLARE @GECGUNID int

-- BÝR ÖNCEKÝ GÜNÜN FÝYATI O OLACAK VE GUNUN ÜRÜNLERÝ TABLOSUNDA SÝLÝNECEK
SET @GECGUNID = (SELECT urunId FROM dbo.tbl_gununUrunleri WHERE tarih=CONVERT(VARCHAR(10),DATEADD(DD, -1, GETDATE()),111))
IF (@GECGUNID > 0)
	BEGIN
		UPDATE dbo.tbl_urunler SET uIndirimFiyat='0' WHERE id=@GECGUNID
		DELETE dbo.tbl_gununUrunleri WHERE tarih=CONVERT(VARCHAR(10),DATEADD(DD, -1, GETDATE()),111)
	END

-- BU GÜNÜN ÜRÜNÜ BULUNUP ÜRÜNLER TABLODUNDA FÝYAT GÜNCELLENECEK
SET @GUNFIYAT = (SELECT satisFiyat FROM dbo.tbl_gununUrunleri WHERE tarih=CONVERT(VARCHAR(10),GETDATE(),111))
SET @GUNID = (SELECT urunId FROM dbo.tbl_gununUrunleri WHERE tarih=CONVERT(VARCHAR(10),GETDATE(),111))
IF(@GUNID > 0)
	BEGIN
		UPDATE dbo.tbl_urunler SET uIndirimFiyat=@GUNFIYAT WHERE id=@GUNID
	END



